language: scala

jdk: openjdk8

scala:
  - 2.13.3

script:
  - sbt -Dfile.encoding=UTF8 ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - joseinn@correo.ugr.es
  on_success: always